[platformio]
src_dir = firmware/src
include_dir = firmware/include

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

; Build flags to expose header directory
build_flags = 
    -I firmware/include